version: '3.8'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    environment:
      - CSVSERVER_BORDER=${CSVSERVER_BORDER}
    env_file: "csvserver.env"
    ports:
      - 9393:9300
    volumes:
      - ./inputFile:/csvserver/inputdata

